name: Build OpenInDiscord Tweak

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Set up Homebrew
      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/opt/homebrew/bin" >> $GITHUB_PATH

      # Step 3: Install Theos dependencies
      - name: Install Dependencies
        run: |
          brew install make ldid

      # Step 4: Install Theos
      - name: Install Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "$THEOS/bin" >> $GITHUB_PATH

      # Step 5: Build the tweak and package as .deb
      - name: Build and Package Tweak
        run: |
          make package

      # Step 6: Upload the .deb file as an artifact
      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openindiscord-deb
          path: packages/*.deb
          if-no-files-found: error
