name: Build OpenInDiscord Tweak

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Install Dependencies
      - name: Install Dependencies
        run: |
          brew install make ldid perl

      # Step 3: Install Theos
      - name: Install Theos
        run: |
          export THEOS=~/theos
          git clone --recursive https://github.com/theos/theos.git $THEOS
          echo "$THEOS/bin" >> $GITHUB_PATH

      # Step 4: Set up iOS SDK
      - name: Set up iOS SDK
        run: |
          export THEOS=~/theos
          SDK_VERSION="16.5"
          SDK_PATH="$THEOS/sdks/iPhoneOS${SDK_VERSION}.sdk"
          if [ ! -d "$SDK_PATH" ]; then
            curl -L -o sdk.tar.xz "https://github.com/theos/sdks/releases/download/master-146e41f/iPhoneOS16.5.sdk.tar.xz"
            mkdir -p $THEOS/sdks
            tar -C $THEOS/sdks -xJf sdk.tar.xz
          fi

      # Step 5: Build and package the tweak
      - name: Build and Package Tweak
        env:
          THEOS: ~/theos
        run: |
          export PATH="$THEOS/bin:$PATH"
          make clean package FINALPACKAGE=1

      # Step 6: Upload the .deb file as an artifact
      - name: Upload .deb Artifact
        uses: actions/upload-artifact@v4
        with:
          name: openindiscord-deb
          path: packages/*.deb
          if-no-files-found: error
